### ISSUE TITLE
TailwindCSS 2.1 Support 

### ISSUE THREAD

**Issue by muhammadsammy** [muhammadsammy/tailwindcss-classnames#197]
### Project board: https://github.com/muhammadsammy/tailwindcss-classnames/projects/2

- [x]  **Partial support** for the JIT engine features (#204).
- [x] New filter and backdrop-filter utilities (#196)
- [x] New blending mode utilities (#195)
- [x] New isolation utilities (#194)
- [x] New box-decoration-break utilities (#193)
- [x] New inline-table and list-item display utilities (#192)

### How to work on these features
Read: [Adding new features from TailwindCSS](https://github.com/muhammadsammy/tailwindcss-classnames/blob/master/CONTRIBUTING.md#adding-new-features-from-tailwindcss).
