### ISSUE TITLE
Support TailwindCSS v2.2.0

### ISSUE THREAD

**Issue by muhammadsammy** [muhammadsammy/tailwindcss-classnames#229]
### Relevant new features:
- [x] Add `background-origin` utilities (#241)
- [x] Add `empty` variant (#240)
- [x] Add `blur-none` by default with intent to deprecate `blur-0` (#230)
- [x] Rename `lightBlue` to `sky`, emit console warning when using deprecated name (#234)
- [x] JIT: Add universal shorthand color opacity syntax (#239)
- [x] JIT: Add per-side border color utilities (#238)
- [x] JIT: Add support for `before` and `after` pseudo-element variants and `content` utilities (#237)
- [x] JIT: Add exhaustive pseudo-class and pseudo-element variant support (#236)
- [x] JIT: Add new `peer-*` variants for styling based on sibling state (#233)
- [x] JIT: Add `caret-color` utilities (#235)
- [x] JIT: Remove need for `transform` class when using classes like `scale-*`, `rotate-*`, etc. (#232)
- [x] JIT: Remove need for `filter` and `backdrop-filter` classes when using classes like `contrast-*`, `backdrop-blur-*`, etc. (#231)

## How to contribute?

- Working on features:
	- Kindly read the [CONTRIBUTING](https://github.com/muhammadsammy/tailwindcss-classnames/blob/master/CONTRIBUTING.md) doc
	- Comment and choose a feature to be assigned to and work on it

- If you believe that a feature is missing or should be supported, please feel free to comment or open a new issue for it!
