### ISSUE TITLE
Support v3.1.0

### ISSUE THREAD

**Issue by muhammadsammy** [muhammadsammy/tailwindcss-classnames#465]
- [x] Add `text-start` and `text-end` utilities ([#6656](https://github.com/tailwindlabs/tailwindcss/pull/6656))
- [x] Support customizing class name when using `darkMode: 'class'` ([#5800](https://github.com/tailwindlabs/tailwindcss/pull/5800))
- [x] Add new `border-spacing` utilities ([#7102](https://github.com/tailwindlabs/tailwindcss/pull/7102))
- [x] Add `enabled` variant ([#7905](https://github.com/tailwindlabs/tailwindcss/pull/7905))
- [x] Add `backdrop` variant ([#7924](https://github.com/tailwindlabs/tailwindcss/pull/7924), [#8526](https://github.com/tailwindlabs/tailwindcss/pull/8526))
- [x] Add `grid-flow-dense` utility ([#8193](https://github.com/tailwindlabs/tailwindcss/pull/8193))
- [x] Add `mix-blend-plus-lighter` utility ([#8288](https://github.com/tailwindlabs/tailwindcss/pull/8288))
- [x] Add `prefers-contrast` media query variants ([#8410](https://github.com/tailwindlabs/tailwindcss/pull/8410))
- [x] Add `optional` variant ([#8486](https://github.com/tailwindlabs/tailwindcss/pull/8486))
